# Copyright © 2026 Qiantong Technology Co., Ltd.
# qKnow Knowledge Platform
#  *
# License:
# Released under the Apache License, Version 2.0.
# You may use, modify, and distribute this software for commercial purposes
# under the terms of the License.
#  *
# Special Notice:
# All derivative versions are strictly prohibited from modifying or removing
# the default system logo and copyright information.
# For brand customization, please apply for brand customization authorization via official channels.
#  *
# More information: https://qknow.qiantong.tech/business.html
#  *
# ============================================================================
#  *
# 版权所有 © 2026 江苏千桐科技有限公司
# qKnow 知识平台（开源版）
#  *
# 许可协议：
# 本项目基于 Apache License 2.0 开源协议发布，
# 允许在遵守协议的前提下进行商用、修改和分发。
#  *
# 特别说明：
# 所有衍生版本不得修改或移除系统默认的 LOGO 和版权信息；
# 如需定制品牌，请通过官方渠道申请品牌定制授权。
#  *
# 更多信息请访问：https://qknow.qiantong.tech/business.html

# 文件上传配置
dromara:
  x-file-storage: #文件存储配置
    default-platform: local #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    #对应平台的配置写在这里，注意缩进要对齐
    local-plus:
      - platform: local # 存储平台标识
        enable-storage: true  #启用存储
        enable-access: false #启用访问（线上请使用 Nginx 配置，效率更高）
        domain: "" # 访问域名，例如：“http://127.0.0.1:8081/file/”，注意后面要和 path-patterns 保持一致，“/”结尾，本地存储建议使用相对路径，方便后期更换域名
        path-patterns: /** # 访问路径
        base-path: / # 基础路径
        storage-path: ${user.dir}/upload/ # 存储路径
    aliyun-oss:
      - platform: xxxx-oss-xx # 存储平台标识
        enable-storage: true # 启用存储
        access-key: xxxxxxxxxxx # 阿里云访问秘钥
        secret-key: xxxxxxxxxxx # 阿里云秘钥
        end-point: https://abc.oss-cn-shanghai.aliyuncs.com # OSS服务节点
        bucket-name: xxxxx # 存储桶名
        domain: https://abc.oss-cn-shanghai.aliyuncs.com/ # 访问域名，注意“/”结尾，例如：https://abc.oss-cn-shanghai.aliyuncs.com/
    #       base-path: /document # 基础路径
