payment:
  alipay:
    # 应用ID
    appId:
    # 应用私钥
    appPrivateKey:
    # 支付宝公钥
    alipayPublicKey:
    # 回调接口
    notifyUrl:
    # 重定向回来路径
    returnUrl:
    # 沙箱环境支付网地址 正式环境：openapi.alipay.com
    gatewayHost:
    # 沙箱环境支付网地址 正式环境：https://openapi.alipay.com/gateway.do
    gatewayUrl:
  wechat:
    # 应用ID
    appId:
    # 应用私钥
    appPrivateKey:
    # 支付宝公钥
    alipayPublicKey:
    # 回调接口
    notifyUrl:
